name: Running Function- F1

on:
  workflow_dispatch:
    inputs:
      ID:
        description: 'ID'
        required: false
      InvokeName:
        description: 'FunctionInvoke'
        required: true
      FaaSrLog:
        description: 'FaaSrLog'
        required: false

jobs:
  run_docker_image:
    runs-on: ubuntu-latest
    container: nanmu08/ghaction
    env:
      SECRET_PAYLOAD: ${{ secrets.SECRET_PAYLOAD }}
      INPUT_ID: ${{ github.event.inputs.ID }}
      INPUT_INVOKENAME: ${{ github.event.inputs.InvokeName }}
      PAYLOAD_REPO: ${{ vars.PAYLOAD_REPO }}
      INPUT_FAASRLOG: ${{ github.event.inputs.FaaSrLog }}
    steps:
    - name: run Rscript
      run: |
        cd /action
        Rscript faasr_start_invoke_github-actions.R
